apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buffy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "buffy.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_TOKEN: eG94Yi0zMzM5NDk1MTMyLTEzNjc1MzAwODgxNjUtNlc0YjBVSllZVk9Ja3k3MjNvY3JmVGZx
  JIRA_BASIC_AUTH_USER: c2V1bmtpbUBlYS5jb20=
  JIRA_BASIC_AUTH_PASS: eWVvamluc2lob29kYWhlZQ==

